DROP TABLE IF EXISTS residents;

CREATE TABLE residents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    residentName TEXT NOT NULL,
    age TEXT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);